title: Genics Blog
email: contact@genicsblog.com
description: >-
  An open source developer publication aimed at sharing well explained
  tutorials on various topics for the developer community.
baseurl: ""
url: "https://genicsblog.com"
permalink: /:title
twitter_username: "genicsblog"
github_username: "genicsblog"
github_repo: "genicsblog/genicsblog.com"
google_analytics: "G-KQJM9Z9N1Z"
adsense-data-ad-client: "ca-pub-8114751086331659"
adsense-data-display-ad-slot: "8698895132"
adsense-data-infeed-ad-slot: "3535897708"
img_src_prefix:
  general: "https://ik.imagekit.io/genicsblog/tr:f-webp/"
  header: "https://ik.imagekit.io/genicsblog/tr:w-1920,h-1080,f-webp/"
  avatar: "https://ik.imagekit.io/genicsblog/tr:w-128,h-128,f-webp/"

defaults:
  - scope:
      path: "_drafts/*.md"
    values:
      sitemap: false

collections:
  series:
    permalink: /series/:name
    output: true
  drafts:
    permalink: /draft/:name
    output: true
  tools:
    permalink: /tool/:name
    output: true

extlinks:
  attributes: { rel: nofollow noopener noreferrer, target: _blank }
  rel_exclude: ["genicsblog.com", "jekyllex.xyz"]

# Build settings
plugins:
  - jekyll-postcss
  - jekyll-minifier
  - jekyll-archives
  - jekyll-hostname
  - jekyll-paginate-v2
  - jekyll-loading-lazy
  - jekyll-redirect-from
  - jekyll-auto-authors
  - jekyll-url-metadata
  - jekyll-include-cache

pagination:
  enabled: true
  per_page: 9
  permalink: "/page/:num/"
  title: ":title - page :num"
  sort_field: "date"
  sort_reverse: true

autopages:
  enabled: true

  categories:
    layouts:
      - "archive.html"
    title: "Posts in category #:cat"
    permalink: "/category/:cat"
    silent: false
    slugify:
      mode: "default"
      case: true

  collections:
    enabled: false

  tags:
    layouts:
      - "archive.html"
    title: "Posts tagged with #:tag"
    permalink: "/tag/:tag"
    silent: false
    slugify:
      mode: "default"
      case: true

  authors:
    enabled: true
    data: "_data/authors.yml"
    layouts:
      - "author.html"
    title: "Posts by :author"
    permalink: "/author/:author/"
    slugify:
      mode: "default"
      cased: true

postcss:
  cache: false

jekyll-minifier:
  exclude:
    - "sitemap.xml"
    - "assets/css/theme.css"
  uglifier_args:
    harmony: true

include:
  - _pages
  - .nojekyll

exclude:
  - _scripts/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.md
  - dev.sh
  - vercel.json
