name: Publish to staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Checkout main repo
      uses: actions/checkout@v2
      with:
        repository: genicsblog/genicsblog.com
        path: content

    - name: Setup articles and necessary files
      run: |
        mv content/* .
        rm -rf content
        touch .nojekyll
        echo "User-agent: *\nDisallow: /" >> robots.txt

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler-cache: true

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install npm dependencies
      run: npm install

    - name: Build production jekyll site
      run: JEKYLL_ENV=dev NODE_ENV=dev bundle exec jekyll build

    - name: Deploy to gh-pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}