name: Test validation scripts

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install python dependencies
      run: |
        pip install PyYAML python-frontmatter requests

    - name: Run authors validation script tests
      run: |
        ./_scripts/spec/run_tests.sh
